### ISSUE TITLE
카카오톡 OAuth2 관련 문의

### ISSUE THREAD

**Issue by engkimbs** [ihoneymon/boot-spring-boot#6]
안녕하세요 카카오톡으로 OAuth2를 구현하려는 도중 막히는 게 생겨 이슈 남깁니다.

카카오 계정 로그인 창까지 redirect로 갔는데 이 화면에 동의 버튼을 눌렀더니 /error 창으로 redirect되면서 로그인이 되지 않습니다. (페이스북, 구글은 잘 작동합니다.)

혹시 짐작가는 부분이 있을까요?

**Comment by ihoneymon** [comment]
카카오 로그인 관련 내용은 카카오 개발자 포럼에서 문의하시는 게 제일 빠르지 않을까요?

[카카오 로그인 연동 설정](https://devtalk.kakao.com/t/topic/73561)

카카오 로그인 관련 설정 부분에 대해서 기재하고 나시면 더욱 상세한 답변을 받으실 수 있을 듯 합니다.

**Comment by engkimbs** [comment]
네 감사합니다
